-- Create app settings table for Discord configuration
CREATE TABLE IF NOT EXISTS public.app_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create pending notifications queue
CREATE TABLE IF NOT EXISTS public.pending_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  payload JSONB NOT NULL,
  sent BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS pending_notifications_sent_idx 
  ON public.pending_notifications (sent);

-- Enable RLS
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pending_notifications ENABLE ROW LEVEL SECURITY;

-- Admin-only policies for app_settings
CREATE POLICY "Admins can manage app settings"
  ON public.app_settings
  FOR ALL
  USING (has_role(auth.uid(), 'admin'::app_role))
  WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- Admin-only policies for pending_notifications
CREATE POLICY "Admins can view pending notifications"
  ON public.pending_notifications
  FOR SELECT
  USING (has_role(auth.uid(), 'admin'::app_role));

-- System can manage pending notifications (for webhook handler and cron)
CREATE POLICY "System can manage pending notifications"
  ON public.pending_notifications
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Seed default Discord configuration (only if not exists)
INSERT INTO public.app_settings (key, value)
VALUES 
  ('discord.webhooks', '{
    "channels": [{"name": "Operations", "webhook_url": ""}],
    "immediate_channel": "Operations",
    "queued_channel": "Operations"
  }'::jsonb),
  ('discord.mention', '{
    "enabled": true,
    "role_id": ""
  }'::jsonb),
  ('discord.templates', '{
    "immediate": "<@&{role_id}> New **eBay** order received!\\n• Order ID: {id}\\n• Customer: {customer_name}\\n• Total: {total}",
    "queued": "<@&{role_id}> Queued **eBay** order from off-hours:\\n• Order ID: {id}\\n• Customer: {customer_name}\\n• Total: {total}"
  }'::jsonb)
ON CONFLICT (key) DO NOTHING;