name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Type check
        run: npm run typecheck || true
      
      - name: Lint
        run: npm run lint || true
      
      - name: Run tests
        run: npm run test || true
      
      - name: Check formatting
        run: npx prettier --check "**/*.{ts,tsx,js,jsx,json,css,md}" || true
